image:
  file: .gitpod.dockerfile
ports:
- port: 1500
  onOpen: notify
- port: 1501
  onOpen: open-preview
- port: 1502
  onOpen: open-browser
- port: 1503
  onOpen: ignore
- port: 2000-2999
  onOpen: notify
- port: 3000-3999
  onOpen: open-preview
- port: 4000-4999
  onOpen: open-browser
- port: 5000-5999
  onOpen: ignore
- port: 6999-6000
  onOpen: ignore
vscode:
  extensions:
    - wayou.vscode-todo-highlight@1.0.4:8IqxuxCVol2WnScJc5xVzg==
